### ISSUE TITLE
DEV: Leaderboard

### ISSUE THREAD

**Issue by SimonRand2003** [RainierBastiaans/BP_18#72]
Als een user 
wil ik een leaderboard zien op het einde van het spel 
zodat ik een game-achtig gevoel krijg van competitie met andere spelers en gemotiveerd ben om het beste resultaat te halen

**Comment by RainierBastiaans** [comment]
Als een user 
wil ik een leaderboard zien op het einde van het spel 
zodat ik een game-achtig gevoel krijg van competitie met andere spelers en gemotiveerd ben om het beste resultaat te halen
